# Generated by Django 2.0.8 on 2018-09-05 14:47

from django.db import migrations


def cb_seed_items(apps, schema_editor):
    Item = apps.get_model('app', 'Item')
    Item.objects.get(name='This one is not there')


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(cb_seed_items),
    ]
